version: '3.1'
services:
  backend:
    build: ./WFB.Backend
    volumes:
      - ./WFB.Backend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    entrypoint: ["wagi", "-c", "./api.toml", "--log-dir", "./logs", "-l", "0.0.0.0:3000"]
  frontend:
    build: ./WFB.Frontend
    depends_on:
      - backend
    volumes:
      - .:/app
    working_dir: /app/WFB.Frontend
    ports:
      - "8080:8080"
    entrypoint: ["dotnet", "run"]
  backend-api:
    build: ./WFB.BackendApi
    platform: wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    ports:
      - "8081:8080"